### ISSUE TITLE
Investigate why Objection 1.6.7 crashes

### ISSUE THREAD

**Issue by codeheroics** [StartupsPoleEmploi/zen#146]
https://github.com/StartupsPoleEmploi/zen/pull/144

calls to `declaration.$query().upsertGraph()` crashed.

**Comment by codeheroics** [comment]
Answer from the Objection repo: This is not maintained and was never officially supposed to work.

All `upsertGraph()` calls will need to be called from the model (eg. `Declaration.query().upsertGraph({ data })` to upgrade Objection.

**Comment by ecbe5510** [comment]
plus d'evolutions
