### ISSUE TITLE
Fix HTTP 502 Bad Gateway errors on QA logout

### ISSUE THREAD

**Issue by codeheroics** [StartupsPoleEmploi/zen#170]
Trying to logout on the Zen QA environment causes nginx 502 HTTP to be sent, instead of the user being correctly redirected to the homepage.

The user seems to be correctly disconnected, as navigating to the website again correctly displays the homepage.

The issue seems to be related to the size of the redirection URL: On the QA environment, the `idToken` (which we get on user login) that we need to send to disconnect the user (cf. the [PE Store documentation](https://www.emploi-store-dev.fr/portail-developpeur-cms/home/catalogue-des-api/documentation-des-api/utiliser-les-api/authorization-code-flow/avec-authentification-etape-4.html)) is way bigger than in production, resulting node trying to redirect us to URLs like the following:

```
https://authentification-candidat-r.pe-qvr.fr/compte/deconnexion/compte/deconnexion?id_token_hint=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6InpoQm9mYlp3K2prWlpqWHMyOGZHZnp4WmdNOD0ifQ.eyJ0b2tlbk5hbWUiOiJpZF90b2tlbiIsImF6cCI6IlBBUl96ZW5yZWNldHRlXzVhMzg3YWMwOTg4ZDhkYjRjNzllMzdjYTE3MmE5MmZjM2E4ZWM5MWVlOWNlNjk0YWNhM2Y3NDMyNjNiZDMxMTkiLCJzdWIiOiIxZTY2M2JlYi0xMGZkLTQxMTktYTMyNi02OTEyYTY0ZGJmYTMiLCJhdF9oYXNoIjoiNU1hUnBiNGlNRHJ2WWVvYmlDbUE3ZyIsImlzcyI6Imh0dHBzOi8vYXV0aGVudGlmaWNhdGlvbi1jYW5kaWRhdC1yLnBlLXF2ci5mcjo0NDMvY29ubmV4aW9uL29hdXRoMiIsIm9yZy5mb3JnZXJvY2sub3BlbmlkY29ubmVjdC5vcHMiOiJlMWM4Mzc5MC05ZTRkLTRjMDktYmRkMS1jZTFjNDA5YjU5ZTEiLCJnaXZlbl9uYW1lIjoiR0hJU0xBSU5FIiwiaWF0IjoxNTU4NTM0NjcyLCJhdXRoX3RpbWUiOjE1NTg1MzQ2NzAsImV4cCI6MTU1ODUzODI3MiwidG9rZW5UeXBlIjoiSldUVG9rZW4iLCJ1cGRhdGVkX2F0IjoiMCIsImF1ZGl0VHJhY2tpbmdJZCI6IjNmZjU3MjAwLTYzYTQtNDEwYi05ZTcxLTEwNzEyMWYwYzg0ZS0xMTkxNDMiLCJub25jZSI6IjYxNmVlZTA3MzQ5MWUzYmFiN2VhMGFhMGE0NDRmZmJiMTc4Y2M5OTZjZDNhOWI2Yjc0NjYwZDNjNjg4MWIyOTA3NTkzMDIwNzMwMTdiZDY0ZDBkYTgxZTc3NGQ4NDdiMGRjOTc2ODIzOTk2ZDUzZDZlMzM3MWYwYjRkOGQ1NTljIiwicmVhbG0iOiIvaW5kaXZpZHUiLCJlbWFpbCI6ImdoaXNsYWluZS5wYXVsQHdhbmFkb28uZnIiLCJhdWQiOiJQQVJfemVucmVjZXR0ZV81YTM4N2FjMDk4OGQ4ZGI0Yzc5ZTM3Y2ExNzJhOTJmYzNhEGVjOTFlZTljZTY5NGFjYTNmNzQzMjYzYmQzMTE5IiwiaWRJZGVudGl0ZUV4dGVybmUiOiIxZTY2M2JlYi0xMGZkLTQxMTktYTMyNi02OTEyYTY0ZGJmYTMiLCJtaWdyZSI6dHJ1ZSwiZ2VuZGVyIjoiZmVtYWxlIiwiZmFtaWx5X25hbWUiOiJQQVVMIiwiY19oYXNoIjoiZkI1UWhTVnBvUkludW9XQm1tbDFVUSJ9.WPUnSYybji45gw4ZVLr5yzUdMaDIItr3zcojXOgayzakDzs0PSckXbU81xSyZBNekXtcijmYhDqawm0l_F1b_VGicpX6VrjEbiRMmxBz8Y1ppXTGROmw0OtPY0unaak2b9bx6UI_FDrZjPlGeQ8gRyM4TIc2KY9PoC5uAxSjKwlLbdkfyVqafrO-3eZ7YTrAehWfHrAAqfVVdYLDYMCfOyYaDVOgz5hq5i8UFMB-jOstdNrhjSbZmPiMq_a4hYLszpYZlfXzBJ1dtsyph1diunGBmV3kT1ce42t972J79u4vG99dc8DXT-fAjxCtZJBu8RyG4RMYnUVsm3rLAXm7pw&redirect_uri=http://zen.beta.pole-emploi.fr
```

Reducing the size of the `id_token_hint` query parameter fixes the issue, which means that the problem seems to be that.

However, as of the writing of this issue, I cannot reproduce the issue on my development environment, and I have been unable to find any differences between the two environments (versions of node, 10.15.0, and of nginx 1.13.12, are the same on both environments)

This is not a problem for now, but could become a big source of errors if pole-emploi propagates a change that makes their id_token bigger in production too.

**Comment by ecbe5510** [comment]
Plus d'evolutions sur zen hors demandes specifiques
